FROM node:20-bookworm

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

COPY clients/web/package*.json ./

RUN npm install

COPY clients/web/ ./

RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npm run start -- --hostname 0.0.0.0"]